export const layout = [
  ['Monophthongs'],
  ['Diphthongs'],
  ['Stops', 'Affricates'],
  ['Nasals', 'R-colored vowels', 'Liquids', 'Semivowels'],
  ['Fricatives'],
];

export const phonemes = {
  'Monophthongs' : ['AE', 'IH', 'AA', 'EH', 'IY', 'UW', 'AH', 'AO', 'UH'],
  'Diphthongs' : ['AW', 'OY', 'AY', 'EY', 'OW'],
  'Stops' : ['D', 'T', 'G', 'B', 'P', 'K'],
  'Affricates' : ['CH', 'JH'],
  'Nasals' : ['NG', 'M', 'N'],
  'R-colored vowels' : ['ER'],
  'Liquids' : ['R', 'L'],
  'Semivowels' : ['Y', 'W'],
  'Fricatives' : ['F', 'HH', 'SH', 'V', 'ZH', 'DH', 'TH', 'Z', 'S']
};

export const words = {
  'AO': 'ought',
  'AA': 'odd',
  'IY': 'eat',
  'UW': 'two',
  'EH': 'led',
  'IH': 'it',
  'UH': 'hood',
  'AH': 'hut',
  'AE': 'at',
  'EY': 'ate',
  'AY': 'hide',
  'OW': 'oat',
  'AW': 'cow',
  'OY': 'toy',
  'P': 'pee',
  'B': 'be',
  'T': 'tea',
  'D': 'dee',
  'K': 'key',
  'G': 'green',
  'CH': 'cheese',
  'JH': 'gee',
  'F': 'fee',
  'V': 'vow',
  'TH': 'theta',
  'DH': 'thee',
  'S': 'sea',
  'Z': 'zip',
  'SH': 'she',
  'ZH': 'seizure',
  'HH': 'he',
  'M': 'me',
  'N': 'knee',
  'NG': 'ping',
  'ER': 'hurt',
  'L': 'late',
  'R': 'read',
  'Y': 'yield',
  'W': 'we'
};
